/* PLEASE DON'T EDIT THIS FILE AS IT'S AUTOGENERATED. 
 * The source is index.coffee. Change that.
 */

(function() {
  var approximate, format;
  approximate = function(num, options) {
    var units;
    if (options == null) {
      options = {};
    }
    units = {
      'thousand': 'K',
      'million': 'M',
      'billion': 'B'
    };
    if (options['units'] != null) {
      if (options['units']['billion'] != null) {
        units['billion'] = options['units']['billion'];
      }
      if (options['units']['million'] != null) {
        units['million'] = options['units']['million'];
      }
      if (options['units']['thousand'] != null) {
        units['thousand'] = options['units']['thousand'];
      }
    }
    num = parseInt(num);
    if (Math.abs(num) >= 999950000) {
      return format(num, 1000000000, units['billion']);
    } else if (Math.abs(num) >= 999950) {
      return format(num, 1000000, units['million']);
    } else if (Math.abs(num) >= 1000) {
      return format(num, 1000, units['thousand']);
    } else {
      return num + '';
    }
  };
  format = function(num, divisor, suffix) {
    var decimals;
    num = num / divisor;
    decimals = Math.abs(num) < 10 ? 1 : 0;
    num = num.toFixed(decimals).replace('1000', '999');
    return num.replace(/\.0+$/, '') + suffix;
  };
  if ((typeof module !== "undefined" && module !== null) && module.exports) {
    module.exports = approximate;
  } else {
    window.approximate = approximate;
  }
}).call(this);
